/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 C:\Users\taham\Hackathon\NASA-HACKS\src\assets\Rocket\saturn_v_-_nasa\scene.gltf 
Author: Stanley Creative (https://sketchfab.com/Stanley_Creative)
License: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
Source: https://sketchfab.com/3d-models/saturn-v-nasa-7a2c9709ff8144c8b3b18ec84b5e112e
Title: Saturn V - NASA
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, -99.185]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -4.703, 0]}>
            <group position={[0, -0.003, 0]}>
              <mesh geometry={nodes.Object_13_1.geometry} material={materials.material_0} position={[0, -0.198, 0]} />
              <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_15.geometry} material={materials.material_0} position={[0, -0.43, 0]} />
            </group>
            <group position={[-1.955, 0.132, 0]}>
              <group position={[-0.037, 0, 0]} rotation={[0, 0, 0.052]}>
                <group position={[0, 1.515, 0]} rotation={[0, 0, -Math.PI / 2]}>
                  <mesh geometry={nodes.Object_21_1.geometry} material={materials.material_0} />
                  <mesh geometry={nodes.Object_23_1.geometry} material={materials.material_0} position={[-0.001, -0.038, 0]} />
                </group>
                <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
              </group>
              <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} />
            </group>
            <mesh geometry={nodes.Object_8.geometry} material={materials.Apollo_Metal} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.material_0} position={[0, 3.101, 0]} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.material_0} position={[0, 2.136, 0]} rotation={[0, Math.PI / 4, 0]} />
          </group>
          <mesh geometry={nodes.Object_6.geometry} material={materials.Apollo_Metal} />
        </group>
        <group position={[0, 0, -102.406]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_29.geometry} material={materials.White} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Black} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.Apollo_Metal} position={[0, -3.221, 0]} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} position={[0, 1.118, 0]} rotation={[0, Math.PI / 4, 0]} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.material_0} position={[0, 1.118, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} position={[0, 1.118, 0]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.material_0} position={[0, 1.118, 0]} rotation={[0, -Math.PI / 4, 0]} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[0, 0.436, Math.PI / 4]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[Math.PI, 1.134, -2.356]} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[Math.PI, -0.436, -2.356]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[0, -1.134, Math.PI / 4]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[0, -0.436, -Math.PI / 4]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[0, 1.134, -Math.PI / 4]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[Math.PI, 0.436, 2.356]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[-Math.PI, -1.134, 2.356]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} position={[0, -0.595, 0]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.material_0} position={[0, -0.595, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.material_0} position={[0, -0.595, 0]} rotation={[Math.PI, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.material_0} position={[0, -0.595, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.material_0} position={[0, -0.351, 0]} rotation={[0, 0, -1.169]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.material_0} position={[0, -0.088, 0]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.material_0} position={[0, -0.088, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_72.geometry} material={materials.material_0} position={[0, -0.088, 0]} rotation={[Math.PI, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.material_0} position={[0, -0.088, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_76.geometry} material={materials.material_0} position={[0, -0.351, 0]} rotation={[-1.169, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.material_0} position={[0, -0.351, 0]} rotation={[Math.PI, 0, 1.972]} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.material_0} position={[0, -0.351, 0]} rotation={[1.169, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_82.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_84.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[-Math.PI / 4, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_86.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[Math.PI, 0, 2.356]} />
          <mesh geometry={nodes.Object_88.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[Math.PI / 4, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_90.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[-Math.PI / 4, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[Math.PI, 0, 2.356]} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[Math.PI / 4, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.Black} position={[0, 1.023, 0.604]} rotation={[-Math.PI / 6, 0, 0]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.Black} position={[0.604, 1.023, 0]} rotation={[-Math.PI / 2, Math.PI / 3, Math.PI / 2]} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.Black} position={[0, 1.023, -0.604]} rotation={[-2.618, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_104.geometry} material={materials.Black} position={[-0.604, 1.023, 0]} rotation={[-Math.PI / 2, -Math.PI / 3, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.material_0} position={[0, 0.565, 0]} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 4.28, 0]} scale={[1, 1, 0.962]}>
            <mesh geometry={nodes.Object_120.geometry} material={materials.Apollo_Metal} />
            <mesh geometry={nodes.Object_122.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
            <mesh geometry={nodes.Object_124.geometry} material={materials.Apollo_Metal} position={[-0.973, 1.852, 0.953]} rotation={[-Math.PI, 0.645, -Math.PI]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_126.geometry} material={materials.Apollo_Metal} position={[-0.973, 1.452, 0.953]} rotation={[-Math.PI, 0.645, -Math.PI]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_128.geometry} material={materials.Apollo_Metal} position={[-0.973, 1.052, 0.953]} rotation={[-Math.PI, 0.645, -Math.PI]} scale={[1.001, 1, 1.001]} />
          </group>
          <group position={[3.5, 4.28, 3.5]} scale={[1, 1, 0.962]}>
            <mesh geometry={nodes.Object_130.geometry} material={materials.Apollo_Metal} />
            <mesh geometry={nodes.Object_132.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_134.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.852, -0.977]} rotation={[0, 0.785, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_136.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.452, -0.977]} rotation={[0, 0.785, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_138.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.052, -0.977]} rotation={[0, 0.785, 0]} scale={[1.001, 1, 1.001]} />
          </group>
          <group position={[3.5, 4.28, -3.5]} rotation={[0, Math.PI / 2, 0]} scale={[0.962, 1, 1]}>
            <mesh geometry={nodes.Object_140.geometry} material={materials.Apollo_Metal} />
            <mesh geometry={nodes.Object_142.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_144.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.852, -0.94]} rotation={[0, 0.746, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_146.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.452, -0.94]} rotation={[0, 0.746, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_148.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.052, -0.94]} rotation={[0, 0.746, 0]} scale={[1.001, 1, 1.001]} />
          </group>
          <group position={[-3.5, 4.28, -3.5]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, 0.962]}>
            <mesh geometry={nodes.Object_150.geometry} material={materials.Apollo_Metal} />
            <mesh geometry={nodes.Object_152.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_154.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.852, -0.977]} rotation={[0, 0.786, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_156.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.452, -0.977]} rotation={[0, 0.786, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_158.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.052, -0.977]} rotation={[0, 0.786, 0]} scale={[1.001, 1, 1.001]} />
          </group>
          <group position={[-3.5, 4.28, 3.5]} rotation={[0, -Math.PI / 2, 0]} scale={[0.962, 1, 1]}>
            <mesh geometry={nodes.Object_160.geometry} material={materials.Apollo_Metal} />
            <mesh geometry={nodes.Object_162.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_164.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.852, -0.94]} rotation={[0, 0.747, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_166.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.452, -0.94]} rotation={[0, 0.747, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_168.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.052, -0.94]} rotation={[0, 0.747, 0]} scale={[1.001, 1, 1.001]} />
          </group>
          <mesh geometry={nodes.Object_110.geometry} material={materials.Saturn_V_Main} />
          <mesh geometry={nodes.Object_112.geometry} material={materials.Saturn_V_Main} />
          <mesh geometry={nodes.Object_114.geometry} material={materials.Saturn_V_Main} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_116.geometry} material={materials.Saturn_V_Main} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_118.geometry} material={materials.Saturn_V_Main} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_170.geometry} material={materials.material_0} position={[0, 6.536, 0]} scale={[1, 1, 0.962]} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.material_0} position={[0, 6.557, 0]} scale={[1, 1, 0.962]} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.Saturn_V_Main} scale={[1, 1, 0.962]} />
          <mesh geometry={nodes.Object_176.geometry} material={materials.material_0} position={[0, 6.47, 0]} rotation={[0, 0.785, 0]} scale={[0.981, 1, 0.981]} />
          <mesh geometry={nodes.Object_178.geometry} material={materials.material_0} position={[0, 6.47, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.962, 1, 1]} />
          <mesh geometry={nodes.Object_180.geometry} material={materials.Saturn_V_Main} position={[0, 9.426, 0]} />
          <mesh geometry={nodes.Object_182.geometry} material={materials.material_0} position={[-0.98, 6.404, -5.192]} rotation={[-Math.PI, 1.374, -Math.PI]} />
        </group>
        <group position={[0, 0, -42.1]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 2.922, 0]}>
            <mesh geometry={nodes.Object_216.geometry} material={materials.Saturn_V_Main} />
            <mesh geometry={nodes.Object_219.geometry} material={materials.material_0} rotation={[0, -Math.PI / 4, 0]} />
          </group>
          <group position={[0, 7.835, 0]} rotation={[0, 0.611, 0]}>
            <mesh geometry={nodes.Object_222.geometry} material={materials.material_0} rotation={[0, -Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object_224.geometry} material={materials.material_0} rotation={[-Math.PI, 0.107, -Math.PI]} />
          </group>
          <mesh geometry={nodes.Object_184.geometry} material={materials.Saturn_V_Main} />
          <mesh geometry={nodes.Object_186.geometry} material={materials.material_0} position={[0.717, 4.587, 3.606]} rotation={[0, -1.374, -0.587]} />
          <mesh geometry={nodes.Object_188.geometry} material={materials.material_0} position={[3.605, 4.587, 0.717]} rotation={[0, -0.196, -0.587]} />
          <mesh geometry={nodes.Object_190.geometry} material={materials.material_0} position={[3.605, 4.587, -0.717]} rotation={[0, 0.196, -0.587]} />
          <mesh geometry={nodes.Object_192.geometry} material={materials.material_0} position={[0.717, 4.587, -3.605]} rotation={[0, 1.374, -0.587]} />
          <mesh geometry={nodes.Object_194.geometry} material={materials.material_0} position={[-0.718, 4.587, -3.605]} rotation={[Math.PI, 1.374, 2.555]} />
          <mesh geometry={nodes.Object_196.geometry} material={materials.material_0} position={[-3.606, 4.587, -0.717]} rotation={[-Math.PI, 0.196, 2.555]} />
          <mesh geometry={nodes.Object_198.geometry} material={materials.material_0} position={[-3.606, 4.587, 0.718]} rotation={[-Math.PI, -0.196, 2.555]} />
          <mesh geometry={nodes.Object_200.geometry} material={materials.material_0} position={[-0.717, 4.587, 3.606]} rotation={[-Math.PI, -1.374, 2.555]} />
          <mesh geometry={nodes.Object_202.geometry} material={materials.material_0} position={[0, 3.94, 0]} rotation={[0, Math.PI / 4, 0]} />
          <mesh geometry={nodes.Object_204.geometry} material={materials.material_0} position={[0, 2.311, 0]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_206.geometry} material={materials.material_0} position={[1.949, 2.311, -1.949]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_208.geometry} material={materials.material_0} position={[-1.949, 2.311, 1.949]} rotation={[0, Math.PI / 4, 0]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.material_0} position={[-1.949, 2.311, -1.949]} rotation={[0, -Math.PI / 4, 0]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_212.geometry} material={materials.material_0} position={[1.949, 2.311, 1.949]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_214.geometry} material={materials.material_0} position={[-2.038, 5.556, -4.874]} rotation={[-Math.PI, 1.165, -Math.PI]} />
        </group>
        <group position={[0, 0, -78.491]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 9.485, 0]}>
            <group position={[2.271, 0, -2.271]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
              <mesh geometry={nodes.Object_236.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_238.geometry} material={materials.Saturn_V_Main} position={[0, 0, -3.212]} rotation={[0, -Math.PI / 4, 0]} />
            </group>
            <group position={[2.271, 0, 2.271]} rotation={[0, Math.PI / 4, 0]}>
              <mesh geometry={nodes.Object_240.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_242.geometry} material={materials.Saturn_V_Main} position={[0, 0, -3.212]} rotation={[0, -Math.PI / 4, 0]} />
            </group>
            <group position={[-2.271, 0, -2.271]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}>
              <mesh geometry={nodes.Object_244.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_246.geometry} material={materials.Saturn_V_Main} position={[0, 0, -3.212]} rotation={[0, -Math.PI / 4, 0]} />
            </group>
            <group position={[-2.271, 0, 2.271]} rotation={[0, -Math.PI / 4, 0]}>
              <mesh geometry={nodes.Object_248.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_250.geometry} material={materials.Saturn_V_Main} position={[0, 0, -3.212]} rotation={[0, -Math.PI / 4, 0]} />
            </group>
            <mesh geometry={nodes.Object_234.geometry} material={materials.Saturn_V_Main} />
          </group>
          <group position={[0, -11.591, 0]}>
            <group position={[0, 4.098, 0]} rotation={[0, 0.611, 0]}>
              <mesh geometry={nodes.Object_255.geometry} material={materials.material_0} rotation={[0, -Math.PI / 2, 0]} />
            </group>
            <group position={[0, 1.536, 0]} rotation={[0, 0.611, 0]}>
              <mesh geometry={nodes.Object_258.geometry} material={materials.material_0} rotation={[0, -Math.PI / 2, 0]} />
            </group>
            <mesh geometry={nodes.Object_252.geometry} material={materials.Saturn_V_Main} />
          </group>
          <mesh geometry={nodes.Object_226.geometry} material={materials.Saturn_V_Main} />
          <mesh geometry={nodes.Object_228.geometry} material={materials.material_0} position={[0, -2.727, -3.193]} />
          <mesh geometry={nodes.Object_230.geometry} material={materials.material_0} position={[3.311, 1.87, 0]} />
          <mesh geometry={nodes.Object_232.geometry} material={materials.material_0} position={[0, -7.09, 0]} scale={[0.57, 0.532, 0.57]} />
        </group>
        <mesh geometry={nodes.Object_108.geometry} material={materials.material_0} position={[0, 0, -90.94]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
