/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: Battle_Dude (https://sketchfab.com/1546809)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/saturn-v-6943bd3227f94bcaba1a7e13f8d5d4ea
Title: Saturn V
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, -99.185]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -4.703, 0]}>
            <group position={[0, -0.003, 0]}>
              <mesh geometry={nodes.Object_20_1.geometry} material={materials.material_0} position={[0, -0.198, 0]} />
              <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} position={[0, -0.43, 0]} />
              <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} />
            </group>
            <group position={[-1.955, 0.132, 0]}>
              <group position={[-0.037, 0, 0]} rotation={[0, 0, 0.052]}>
                <group position={[0, 1.515, 0]} rotation={[0, 0, -Math.PI / 2]}>
                  <mesh geometry={nodes.Object_35_1.geometry} material={materials.material_0} position={[-0.001, -0.038, 0]} />
                  <mesh geometry={nodes.Object_32_1.geometry} material={materials.material_0} />
                </group>
                <mesh geometry={nodes.Object_29.geometry} material={materials.material_0} />
              </group>
              <mesh geometry={nodes.Object_26.geometry} material={materials.material_0} />
            </group>
            <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} position={[0, 3.101, 0]} />
            <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} position={[0, 2.136, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Apollo_Metal} />
          </group>
          <mesh geometry={nodes.Object_10.geometry} material={materials.Apollo_Metal} />
        </group>
        <group position={[0, 0, -102.406]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_49.geometry} material={materials.Apollo_Metal} position={[0, -3.221, 0]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} position={[0, 1.118, 0]} rotation={[0, Math.PI / 4, 0]} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.material_0} position={[0, 1.118, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} position={[0, 1.118, 0]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.material_0} position={[0, 1.118, 0]} rotation={[0, -Math.PI / 4, 0]} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[0, 0.436, Math.PI / 4]} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[Math.PI, 1.134, -2.356]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[Math.PI, -0.436, -2.356]} />
          <mesh geometry={nodes.Object_73.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[0, -1.134, Math.PI / 4]} />
          <mesh geometry={nodes.Object_76.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[0, -0.436, -Math.PI / 4]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[0, 1.134, -Math.PI / 4]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Object_82.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[Math.PI, 0.436, 2.356]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Object_85.geometry} material={materials.material_0} position={[0, 0.565, 0]} rotation={[-Math.PI, -1.134, 2.356]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Object_88.geometry} material={materials.material_0} position={[0, -0.595, 0]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_91.geometry} material={materials.material_0} position={[0, -0.595, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.material_0} position={[0, -0.595, 0]} rotation={[Math.PI, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.material_0} position={[0, -0.595, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.material_0} position={[0, -0.351, 0]} rotation={[0, 0, -1.169]} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.material_0} position={[0, -0.088, 0]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.material_0} position={[0, -0.088, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.material_0} position={[0, -0.088, 0]} rotation={[Math.PI, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_112.geometry} material={materials.material_0} position={[0, -0.088, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_115.geometry} material={materials.material_0} position={[0, -0.351, 0]} rotation={[-1.169, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_118.geometry} material={materials.material_0} position={[0, -0.351, 0]} rotation={[Math.PI, 0, 1.972]} />
          <mesh geometry={nodes.Object_121.geometry} material={materials.material_0} position={[0, -0.351, 0]} rotation={[1.169, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_124.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_127.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[-Math.PI / 4, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_130.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[Math.PI, 0, 2.356]} />
          <mesh geometry={nodes.Object_133.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[Math.PI / 4, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_136.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[0, 0, -Math.PI / 4]} />
          <mesh geometry={nodes.Object_139.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[-Math.PI / 4, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_142.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[Math.PI, 0, 2.356]} />
          <mesh geometry={nodes.Object_145.geometry} material={materials.material_0} position={[0, -0.827, 0]} rotation={[Math.PI / 4, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_148.geometry} material={materials.Black} position={[0, 1.023, 0.604]} rotation={[-Math.PI / 6, 0, 0]} />
          <mesh geometry={nodes.Object_151.geometry} material={materials.Black} position={[0.604, 1.023, 0]} rotation={[-Math.PI / 2, Math.PI / 3, Math.PI / 2]} />
          <mesh geometry={nodes.Object_154.geometry} material={materials.Black} position={[0, 1.023, -0.604]} rotation={[-2.618, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_157.geometry} material={materials.Black} position={[-0.604, 1.023, 0]} rotation={[-Math.PI / 2, -Math.PI / 3, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_160.geometry} material={materials.material_0} position={[0, 0.565, 0]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.White} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.Black} />
        </group>
        <mesh geometry={nodes.Object_163.geometry} material={materials.material_0} position={[0, 0, -90.94]} rotation={[-Math.PI / 2, 0, 0]} />
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_172.geometry} material={materials.Saturn_V_Main} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_175.geometry} material={materials.Saturn_V_Main} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_178.geometry} material={materials.Saturn_V_Main} rotation={[0, -Math.PI / 2, 0]} />
          <group position={[0, 4.28, 0]} scale={[1, 1, 0.962]}>
            <mesh geometry={nodes.Object_184.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
            <mesh geometry={nodes.Object_187.geometry} material={materials.Apollo_Metal} position={[-0.973, 1.852, 0.953]} rotation={[-Math.PI, 0.645, -Math.PI]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_190.geometry} material={materials.Apollo_Metal} position={[-0.973, 1.452, 0.953]} rotation={[-Math.PI, 0.645, -Math.PI]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_193.geometry} material={materials.Apollo_Metal} position={[-0.973, 1.052, 0.953]} rotation={[-Math.PI, 0.645, -Math.PI]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_181.geometry} material={materials.Apollo_Metal} />
          </group>
          <group position={[3.5, 4.28, 3.5]} scale={[1, 1, 0.962]}>
            <mesh geometry={nodes.Object_199.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_202.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.852, -0.977]} rotation={[0, 0.785, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_205.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.452, -0.977]} rotation={[0, 0.785, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_208.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.052, -0.977]} rotation={[0, 0.785, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_196.geometry} material={materials.Apollo_Metal} />
          </group>
          <group position={[3.5, 4.28, -3.5]} rotation={[0, Math.PI / 2, 0]} scale={[0.962, 1, 1]}>
            <mesh geometry={nodes.Object_214.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_217.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.852, -0.94]} rotation={[0, 0.746, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_220.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.452, -0.94]} rotation={[0, 0.746, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_223.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.052, -0.94]} rotation={[0, 0.746, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_211.geometry} material={materials.Apollo_Metal} />
          </group>
          <group position={[-3.5, 4.28, -3.5]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, 0.962]}>
            <mesh geometry={nodes.Object_229.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_232.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.852, -0.977]} rotation={[0, 0.786, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_235.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.452, -0.977]} rotation={[0, 0.786, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_238.geometry} material={materials.Apollo_Metal} position={[-0.952, 1.052, -0.977]} rotation={[0, 0.786, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_226.geometry} material={materials.Apollo_Metal} />
          </group>
          <group position={[-3.5, 4.28, 3.5]} rotation={[0, -Math.PI / 2, 0]} scale={[0.962, 1, 1]}>
            <mesh geometry={nodes.Object_244.geometry} material={materials.Apollo_Metal} position={[0, -2.313, 0]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.Object_247.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.852, -0.94]} rotation={[0, 0.747, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_250.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.452, -0.94]} rotation={[0, 0.747, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_253.geometry} material={materials.Apollo_Metal} position={[-0.989, 1.052, -0.94]} rotation={[0, 0.747, 0]} scale={[1.001, 1, 1.001]} />
            <mesh geometry={nodes.Object_241.geometry} material={materials.Apollo_Metal} />
          </group>
          <mesh geometry={nodes.Object_256.geometry} material={materials.material_0} position={[0, 6.536, 0]} scale={[1, 1, 0.962]} />
          <mesh geometry={nodes.Object_259.geometry} material={materials.material_0} position={[0, 6.557, 0]} scale={[1, 1, 0.962]} />
          <mesh geometry={nodes.Object_262.geometry} material={materials.Saturn_V_Main} scale={[1, 1, 0.962]} />
          <mesh geometry={nodes.Object_265.geometry} material={materials.material_0} position={[0, 6.47, 0]} rotation={[0, 0.785, 0]} scale={[0.981, 1, 0.981]} />
          <mesh geometry={nodes.Object_268.geometry} material={materials.material_0} position={[0, 6.47, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.962, 1, 1]} />
          <mesh geometry={nodes.Object_271.geometry} material={materials.Saturn_V_Main} position={[0, 9.426, 0]} />
          <mesh geometry={nodes.Object_274.geometry} material={materials.material_0} position={[-0.98, 6.404, -5.192]} rotation={[-Math.PI, 1.374, -Math.PI]} />
          <mesh geometry={nodes.Object_166.geometry} material={materials.Saturn_V_Main} />
          <mesh geometry={nodes.Object_169.geometry} material={materials.Saturn_V_Main} />
        </group>
        <group position={[0, 0, -42.1]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_280.geometry} material={materials.material_0} position={[0.717, 4.587, 3.606]} rotation={[0, -1.374, -0.587]} />
          <mesh geometry={nodes.Object_283.geometry} material={materials.material_0} position={[3.605, 4.587, 0.717]} rotation={[0, -0.196, -0.587]} />
          <mesh geometry={nodes.Object_286.geometry} material={materials.material_0} position={[3.605, 4.587, -0.717]} rotation={[0, 0.196, -0.587]} />
          <mesh geometry={nodes.Object_289.geometry} material={materials.material_0} position={[0.717, 4.587, -3.605]} rotation={[0, 1.374, -0.587]} />
          <mesh geometry={nodes.Object_292.geometry} material={materials.material_0} position={[-0.718, 4.587, -3.605]} rotation={[-Math.PI, 1.374, 2.555]} />
          <mesh geometry={nodes.Object_295.geometry} material={materials.material_0} position={[-3.606, 4.587, -0.717]} rotation={[-Math.PI, 0.196, 2.555]} />
          <mesh geometry={nodes.Object_298.geometry} material={materials.material_0} position={[-3.606, 4.587, 0.718]} rotation={[-Math.PI, -0.196, 2.555]} />
          <mesh geometry={nodes.Object_301.geometry} material={materials.material_0} position={[-0.717, 4.587, 3.606]} rotation={[-Math.PI, -1.374, 2.555]} />
          <mesh geometry={nodes.Object_304.geometry} material={materials.material_0} position={[0, 3.94, 0]} rotation={[0, Math.PI / 4, 0]} />
          <mesh geometry={nodes.Object_307.geometry} material={materials.material_0} position={[0, 2.311, 0]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_310.geometry} material={materials.material_0} position={[1.949, 2.311, -1.949]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_313.geometry} material={materials.material_0} position={[-1.949, 2.311, 1.949]} rotation={[0, Math.PI / 4, 0]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_316.geometry} material={materials.material_0} position={[-1.949, 2.311, -1.949]} rotation={[0, -Math.PI / 4, 0]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_319.geometry} material={materials.material_0} position={[1.949, 2.311, 1.949]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.57, 0.532, 0.57]} />
          <mesh geometry={nodes.Object_322.geometry} material={materials.material_0} position={[-2.038, 5.556, -4.874]} rotation={[-Math.PI, 1.165, -Math.PI]} />
          <group position={[0, 2.922, 0]}>
            <mesh geometry={nodes.Object_325.geometry} material={materials.Saturn_V_Main} />
            <mesh geometry={nodes.Object_329.geometry} material={materials.material_0} />
          </group>
          <group position={[0, 7.835, 0]} rotation={[0, 0.611, 0]}>
            <mesh geometry={nodes.Object_333.geometry} material={materials.material_0} rotation={[0, -Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object_336.geometry} material={materials.material_0} rotation={[-Math.PI, 0.107, -Math.PI]} />
          </group>
          <mesh geometry={nodes.Object_277.geometry} material={materials.Saturn_V_Main} />
        </group>
        <group position={[0, 0, -78.491]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_342.geometry} material={materials.material_0} position={[0, -2.727, -3.193]} />
          <mesh geometry={nodes.Object_345.geometry} material={materials.material_0} position={[3.311, 1.87, 0]} />
          <mesh geometry={nodes.Object_348.geometry} material={materials.material_0} position={[0, -7.09, 0]} scale={[0.57, 0.532, 0.57]} />
          <group position={[0, 9.485, 0]}>
            <group position={[2.271, 0, -2.271]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
              <mesh geometry={nodes.Object_357.geometry} material={materials.Saturn_V_Main} position={[0, 0, -3.212]} rotation={[0, -Math.PI / 4, 0]} />
              <mesh geometry={nodes.Object_354.geometry} material={materials.material_0} />
            </group>
            <group position={[2.271, 0, 2.271]} rotation={[0, Math.PI / 4, 0]}>
              <mesh geometry={nodes.Object_363.geometry} material={materials.Saturn_V_Main} position={[0, 0, -3.212]} rotation={[0, -Math.PI / 4, 0]} />
              <mesh geometry={nodes.Object_360.geometry} material={materials.material_0} />
            </group>
            <group position={[-2.271, 0, -2.271]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}>
              <mesh geometry={nodes.Object_369.geometry} material={materials.Saturn_V_Main} position={[0, 0, -3.212]} rotation={[0, -Math.PI / 4, 0]} />
              <mesh geometry={nodes.Object_366.geometry} material={materials.material_0} />
            </group>
            <group position={[-2.271, 0, 2.271]} rotation={[0, -Math.PI / 4, 0]}>
              <mesh geometry={nodes.Object_375.geometry} material={materials.Saturn_V_Main} position={[0, 0, -3.212]} rotation={[0, -Math.PI / 4, 0]} />
              <mesh geometry={nodes.Object_372.geometry} material={materials.material_0} />
            </group>
            <mesh geometry={nodes.Object_351.geometry} material={materials.Saturn_V_Main} />
          </group>
          <group position={[0, -11.591, 0]}>
            <group position={[0, 4.098, 0]} rotation={[0, 0.611, 0]}>
              <mesh geometry={nodes.Object_382.geometry} material={materials.material_0} rotation={[0, -Math.PI / 2, 0]} />
            </group>
            <group position={[0, 1.536, 0]} rotation={[0, 0.611, 0]}>
              <mesh geometry={nodes.Object_386.geometry} material={materials.material_0} rotation={[0, -Math.PI / 2, 0]} />
            </group>
            <mesh geometry={nodes.Object_378.geometry} material={materials.Saturn_V_Main} />
          </group>
          <mesh geometry={nodes.Object_339.geometry} material={materials.Saturn_V_Main} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
